application: link-drop
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /api/.*
  login: required
  secure: always
  script: api.app

- url: /jobs/.*
  script: jobs.app

- url: /tasks/.*
  script: tasks.app

- url: /
  script: app.app
  secure: always

- url: /links/.*
  secure: always
  script: app.app

- url: /.*
  login: required
  secure: always
  script: app.app

libraries:
- name: jinja2
  version: latest

skip_files:
- ^src$
- ^.ve$
- webpack.config.js
- ^(.*/)?.*\.py[co]$
